CREATE TABLE leaderboards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    score_strategy VARCHAR(20) NOT NULL DEFAULT 'BEST_ONLY',
    archive_on_reset BOOLEAN NOT NULL,
    max_score DOUBLE PRECISION,
    min_score DOUBLE PRECISION,
    next_reset_at TIMESTAMPTZ,
    reset_frequency VARCHAR(50) NOT NULL,
    sort_order VARCHAR(10) NOT NULL
);

CREATE INDEX idx_leaderboard_slug ON leaderboards(slug);

CREATE TABLE score_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leaderboard_id BIGINT NOT NULL REFERENCES leaderboards(id),
    player_alias VARCHAR(255) NOT NULL,
    score_value DOUBLE PRECISION NOT NULL,
    submitted_at TIMESTAMPTZ,
    metadata TEXT
);

CREATE INDEX idx_leaderboard_score ON score_entries(leaderboard_id, score_value DESC, submitted_at ASC);
CREATE INDEX idx_leaderboard_player ON score_entries(leaderboard_id, player_alias);

CREATE TABLE score_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leaderboard_slug VARCHAR(255),
    player_alias VARCHAR(255),
    score_value DOUBLE PRECISION NOT NULL,
    submitted_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    reset_label VARCHAR(255),
    metadata TEXT
);

CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_alias VARCHAR(255) NOT NULL UNIQUE,
    banned BOOLEAN,
    banned_at TIMESTAMPTZ,
    banned_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE system_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value TEXT,
    updated_at TIMESTAMPTZ NOT NULL
);